# fly.toml app configuration file generated for alttex-auto on 2025-09-22T21:06:17+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alttex-auto'
