name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json
      - run: npm ci
      - name: Run unit tests (Jest)
        run: npm test -- --ci
        env:
          SHOPIFY_APP_URL: http://localhost:3000
          SHOPIFY_API_KEY: test
          SHOPIFY_API_SECRET: test
          SHOPIFY_SCOPES: read_products,write_products,read_product_listings
          WORKER_URL: http://localhost:8000
          DATABASE_URL: file:./dev.db

  web-e2e:
    runs-on: ubuntu-latest
    needs: web-unit
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json
      - run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          SHOPIFY_APP_URL: http://localhost:3000
          SHOPIFY_API_KEY: test
          SHOPIFY_API_SECRET: test
          SHOPIFY_SCOPES: read_products,write_products,read_product_listings
          WORKER_URL: http://localhost:8000
          DATABASE_URL: file:./dev.db

  worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/worker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt pytest
      - name: Run worker tests
        run: pytest -q

